[project]
name = "portfolio-optimizer"
version = "0.1.0"
description = "Simple Portfolio Optimization Example"
authors = [
    {name = "Mattia",email = "mattia@entropy42.com"}
]
requires-python = "^3.12"
dependencies = [
    "numpy (>=2.5.3,<3.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)",
    "scipy (>=1.18.1,<2.0.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "yfinance (>=1.7.0,<2.0.0)",
    "pyomo (>=6.10.1,<7.0.0)",
    "highspy (>=1.15.1,<2.0.0)",
    "plotly (>=7.1.0,<8.0.0)",
    "nbformat (>=5.11.1,<6.0.0)",
    "z3-solver (>=5.1.0.0,<6.0.0.0)"
]


[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.3.0,<8.0.0)",
    "nbconvert (>=7.17.1,<8.0.0)"
]
